build:
  hugo_version: '0.136.5'
baseURL: "https://enjundu.com/"
title: "Enjun Du（杜恩俊）"
defaultContentLanguage: en
hasCJKLanguage: false
enableEmoji: true
summaryLength: 30

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

markup:
  highlight:
    lineNos: false

params:
  header:
    navbar:
      enable: true
      fixed_to_top: true
      show_search: true
      show_theme_chooser: true
      logo:
        text: "Enjun Du（杜恩俊）"

  footer:
    copyright:
      notice: "© {year} Enjun Du. This work is licensed under CC BY-NC-SA 4.0"
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

menu:
  main:
    - name: Bio
      url: /
      weight: 10
    - name: Papers
      url: /#papers
      weight: 11
    - name: Talks
      url: /#talks
      weight: 12
    - name: News
      url: /#news
      weight: 13
    - name: Experience
      url: /#experience
      weight: 20
    - name: Contact Me
      url: /#contact-me
      weight: 90